language: c

os: linux

cache:
  directories:
    - $HOME/.stack
    - $HOME/.cabal/packages
    - $HOME/.cabal/store

addons:
  apt:
    packages:
      - curl

env:
  jobs:
    - EXEC="stack" RESOLVER="lts-14"

before_install:
  - mkdir -p ~/.local/bin
  - export PATH="$HOME/.local/bin:$PATH"
  - |
      travis_retry curl \
        -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | \
        tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - export STACK="stack --resolver=$RESOLVER"
  - ${STACK} --version
  - ${STACK} test --no-terminal --install-ghc --only-dependencies

script:
  - echo stack=$STACK
  - $STACK --no-terminal build --fast --test --coverage codecov-haskell

after_script:
  - echo stack=$STACK
  - STACK_HPC_ROOT=$($STACK path --local-hpc-root)
  - STACK_TIX=$STACK_HPC_ROOT/codecov-haskell/test-all/test-all.tix
  - STACK_CABAL_VER=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1/hpc
  - STACK_MIX_DIR=$STACK_CABAL_VER
  - echo STACK_TIX=$STACK_TIX
  - echo STACK_MIX_DIR=$STACK_MIX_DIR
  - CODECOV_TOKEN=f70b7e1b-4baf-41c9-af97-901115b93694
  - |
    $STACK exec -- codecov-haskell \
      --tix=$STACK_TIX \
      --mix-dir=$STACK_MIX_DIR \
      --token=$CODECOV_TOKEN \
      --display-report \
      test-all

# env:
#   - GHCVER=7.6.3
#   - GHCVER=7.8.3

# before_install:
#   - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
#   - travis_retry sudo apt-get update
#   - travis_retry sudo apt-get install cabal-install-1.20 ghc-$GHCVER happy
#   - export PATH=/opt/ghc/$GHCVER/bin:$PATH

# install:
#   - cabal-1.20 update
#   - travis_retry sudo apt-get -q -y install hlint || cabal-1.20 install hlint
#   - cabal-1.20 install --only-dependencies --enable-tests --enable-benchmarks

# script:
#   - hlint . --ignore="Parse error"
#   - cabal-1.20 configure --enable-tests --enable-benchmarks --enable-library-coverage -v2
#   - cabal-1.20 build
#   - |
#     if [ $GHCVER = "7.8.3" ]; then
#       cabal-1.20 test --show-details=always
#     else
#       dist/build/run-cabal-test/run-cabal-test --cabal-name=cabal-1.20 --show-details=always
#     fi
#   - cabal-1.20 check
#   - cabal-1.20 sdist
#   - export SRC_TGZ=$(cabal-1.20 info . | awk '{print $2 ".tar.gz";exit}') ;
#     (cd dist/;
#     if [ -f "$SRC_TGZ" ]; then
#       cabal-1.20 install "$SRC_TGZ";
#     else
#       echo "expected '$SRC_TGZ' not found";
#       exit 1;
#     fi)

# after_script:
#   - dist/build/codecov-haskell/codecov-haskell test-all
# --exclude-dir=test --display-report --print-response

# notifications:
#   webhooks:
#   urls:
#     - https://webhooks.gitter.im/e/3ff64a7879ffa1a444b6
#   on_success: change
#   on_failure: always
#   on_start: false
